name: VoronCI PR CI post processing
on:
  workflow_run:
    workflows: ["VoronCI PR Test CI"]
    types:
    - completed
env:
  VORON_TOOLKIT_VERBOSE: true
  VORON_CI_GITHUB_TOKEN: ${{ github.token }}
jobs:
  create_pr_comment:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    permissions:
      pull-requests: write
      checks: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
    - name: Create PR comment 💬
      id: create_pr_comment
      uses: docker://ghcr.io/vorondesign/voron_toolkit_docker:latest
      env:
        PR_HELPER_WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
        PR_HELPER_ARTIFACT_NAME: ci_output
        PR_HELPER_GITHUB_REPOSITORY: ${{ github.repository }}
      with:
        args: set-pr-comment-labels
  upload_imagekit:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}

    runs-on: ubuntu-latest
    steps:
    - name: Upload images to imagekit 📸
      id: imagekit-upload
      uses: docker://ghcr.io/vorondesign/voron_toolkit_docker:latest
      env:
        IMAGEKIT_UPLOADER_WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
        IMAGEKIT_UPLOADER_ARTIFACT_NAME: ci_output
        IMAGEKIT_UPLOADER_GITHUB_REPOSITORY: ${{ github.repository }}
        IMAGEKIT_UPLOADER_PUBLIC_KEY: ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
        IMAGEKIT_UPLOADER_PRIVATE_KEY: ${{ secrets.IMAGEKIT_PRIVATE_KEY }}
        IMAGEKIT_UPLOADER_IMAGEKIT_ENDPOINT: https://ik.imagekit.io/vorondesign
      with:
        args: upload-images
