name: Test Container
run-name: ${{ github.actor }} is testing ${{ github.ref }} 🚀
on:
  workflow_dispatch:
jobs:
    test_job:
      env:
        VORON_CI_OUTPUT: workflow_output
        VORON_CI_STEP_SUMMARY: true
      runs-on: ubuntu-latest
      steps:
      # Checkout the entire repo
      - name: Checkout repo
        uses: actions/checkout@v4
      # Fake tj-actions/changed-files by creating a list of all files in the test directory
      - name: Fake tj-actions/changed-files
        id: list_files
        run: |
          export TEST=$(find ./tests/test_repository_root/printer_mods/ -type f -print)
          echo "FILE_LIST<<EOF" >> $GITHUB_OUTPUT
          echo "$TEST" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      # Sanitize the file list
      - name: Sanitize file list
        id: sanitize_file_list
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        env:
          FILE_LIST_SANITIZE_INPUT: ${{ steps.list_files.outputs.FILE_LIST }}
        with:
          args: sanitize-file-list
      # Run whitespace checks based on files in the test directory
      - name: Whitespace Checker (input_dir)
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        env:
          WHITESPACE_CHECKER_INPUT_DIR: tests/test_repository_root/printer_mods
          WHITESPACE_CHECKER_VERBOSE: true
          WHITESPACE_CHECKER_IGNORE_WARNINGS: false
        with:
          args: check-whitespace
      - name: Mod Structure Checker
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        env:
          MOD_STRUCTURE_CHECKER_INPUT_DIR: tests/test_repository_root/printer_mods
          MOD_STRUCTURE_CHECKER_VERBOSE: true
          MOD_STRUCTURE_CHECKER_IGNORE_WARNINGS: false
        with:
          args: check-mod-structure
      # Run the corruption checker
      - name: Corruption Checker
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        env:
          CORRUPTION_CHECKER_INPUT_DIR: tests/test_repository_root/printer_mods
          CORRUPTION_CHECKER_VERBOSE: true
          CORRUPTION_CHECKER_IGNORE_WARNINGS: true
        with:
          args: check-stl-corruption
      # Run the rotation checker
      - name: Rotation Checker
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        env:
          ROTATION_CHECKER_INPUT_DIR: tests/test_repository_root/printer_mods
          ROTATION_CHECKER_VERBOSE: true
          ROTATION_CHECKER_IGNORE_WARNINGS: true
          ROTATION_CHECKER_IMAGEKIT_ENDPOINT: ./img
          ROTATION_CHECKER_IMAGEKIT_SUBFOLDER: test_run
        with:
          args: check-stl-rotation
      # Generate a README
      - name: Generate README
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        env:
          README_GENERATOR_INPUT_DIR: tests/test_repository_root/printer_mods
          README_GENERATOR_README: true
          README_GENERATOR_VERBOSE: true
          README_GENERATOR_JSON: true
        with:
          args: generate-readme
      # Upload Artifact
      - uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
        with:
          name: ci_output
          path: workflow_output
