name: Test Container
run-name: ${{ github.actor }} is testing ${{ github.ref }} 🚀
on: 
  workflow_dispatch:
jobs:
    test_job:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Echo GITHUB_STEP_SUMMARY
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        with:
            args: debug-container
      - name: LS Repo
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        with:
            args: ls -al /github/workspace
      - name: Test extra env
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        env:
            GITHUB_TOKEN: ${{ github.token }}
        with:
            args: debug-container
        

    