name: Test Container
run-name: ${{ github.actor }} is testing ${{ github.ref }} 🚀
on: 
  workflow_dispatch:
jobs:
    test_job:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Test container
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        with:
          args: which check-stl-corruption
      - name: Echo GITHUB_OUTPUT
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        with:
            args: echo ${GITHUB_OUTPUT}
      - name: Echo GITHUB_STEP_SUMMARY
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        with:
            args: echo ${GITHUB_STEP_SUMMARY}
      - name: LS Repo
        uses: docker://ghcr.io/fheilmann/voron_ci_container:latest
        with:
            args: ls -al /github/workspace

    